spring:
  application:
    name: okr-service
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
AppSecret: 35ea14aa-63fa-4b3d-9707-362b6a2ed65d
